name: Test Examples

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
    name: Test Examples - ubuntu-latest 3.13
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13

      - name: Run tests
        run: uv run pytest -m example
